site_name: CKA Docs
theme:
  name: material
  features:
    - content.code.copy

# Page tree
nav:
  - Home: index.md
  - Cluster Architecture, Installation & Configuration:
    - Backing up an etcd cluster: cluster-architecture-installation-and-configuration/backing-up-an-etcd-cluster.md
    - Certificate Signing Requests (Normal User): cluster-architecture-installation-and-configuration/certificate-signing-requests-normal-user.md
  - Workloads & Scheduling:
    - Deployments: workloads-and-scheduling/deployments.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
